article:
  auto_cover: true
  auto_excerpt: 100
  related_posts:
    enable: true
    title: æ‚¨å¯èƒ½æ„Ÿå…´è¶£çš„æ–‡ç« 
sidebar:
  menu:    
    home: '[ä¸»é¡µ](/)'
    friend: '[å‹é“¾](/friend/)' 
    timeline: '[åŠ¨æ€](/timeline/)'
    about: '[å…³äº](/about/)'
  widgets:
    # ä¸»é¡µ
    home:  search,welcome, recent,timeline
    blog_index: search_blog, recent, timeline
    others: search, welcome, recent, timeline # for 404 and ...
     
    

post-index:
  'æœ‹å‹åœˆ': /friend/rss/

comments:
  service: waline
  waline:
    js: https://unpkg.com/@waline/client@v2/dist/waline.js
    css: https://unpkg.com/@waline/client@v2/dist/waline.css
    # Waline server address url, you should set this to your own link
    serverURL: https://waline.lvbyte.top/
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false

    # Custom locales
    locale:
      placeholder: è¯´ç‚¹ä»€ä¹ˆå§ï¼

    # Custom emoji
    emoji: 
      - https://gcore.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs
      - https://cdn.jsdelivr.net/npm/sticker-heo@2022.7.5/Sticker-100/
      - https://unpkg.com/@waline/emojis@1.1.0/alus
      - https://unpkg.com/@waline/emojis@1.1.0/bilibili
      - https://unpkg.com/@waline/emojis@1.1.0/tw-emoji

    



footer:
  social:
    github:
      icon: '<img src="https://cdn.staticaly.com/gh/Bytelv/lvbyteCdn@main/20230104/github.213d9lnn1c3k.png"/>'
      url: https://github.com/Bytelv
    QQ:
      icon: '<img src="https://cdn.staticaly.com/gh/Bytelv/lvbyteCdn@main/20230104/qqè½»èŠ.52lv7ybhe6ps.png"/>'
      url: http://wpa.qq.com/msgrd?v=3&uin=2015078351&site=qq&menu=yes
    steam:
      icon: '<img src="https://cdn.staticaly.com/gh/Bytelv/lvbyteCdn@main/20230104/steam(1).4jcdvazi3tkw.png"/>'
      url: https://steamcommunity.com/id/lvbyte/
    bilibili:
      icon: '<img src="https://cdn.staticaly.com/gh/Bytelv/lvbyteCdn@main/20230104/bilibili.213uznc82pmo.png"/>'
      url: https://space.bilibili.com/31872009/
    email:
      icon: '<img src="https://cdn.staticaly.com/gh/Bytelv/lvbyteCdn@main/20230104/email.5d1436micpkw.png"/>'
      url: mailto:lvbyte@lvbyte.top
    Twitter:
      icon: '<img src="https://cdn.staticaly.com/gh/Bytelv/lvbyteCdn@main/20230104/æ¨ç‰¹-twitter.6hkubsf8utts.png"/>'
      url: https://twitter.com/lzhji25163047

  content: <span id="busuanzi_container_site_pv">æœ¬å®‡å®™å…±æœ‰<span id="busuanzi_value_site_pv"></span>è‰˜é£èˆ¹ğŸ›¸æ¢ç´¢è¿‡ğŸ‘‹</span>
    å½“å‰é¡µé¢è®¿é—®é‡ <span id="qexo-page-pv">Loading...</span>
    <script src="https://cdn.jsdelivr.net/npm/qexo-static@1.3.0/hexo/statistic/statistic.min.js"></script><br>
    <a href="https://www.travellings.cn/go.html" target="_blank" rel="noopener" title="å¼€å¾€-å‹é“¾æ¥åŠ›">
        <img src="https://www.travellings.cn/assets/logo.gif" alt="å¼€å¾€-å‹é“¾æ¥åŠ›" width="120">
    </a>
  sitemap:
    'åšå®¢':
      - '[è¿‘æœŸ](/)'
      - '[åˆ†ç±»](/categories/)'
      - '[æ ‡ç­¾](/tags/)'
      - '[å½’æ¡£](/archives/)'
    'ç½‘ç«™':
      - '[ä¸ªäººä¸»é¡µ](https://www.lvbyte.top)'
      - '[è¿åŠ¨ç½‘ç«™](https://sport.lvbyte.top)'
      - '[ä¸ªäººäº‘ç›˜](https://cloud.lvbyte.top)'
      - '[éŸ³ä¹ç½‘ç«™](https://music.lvbyte.top)'
      - '[å°ç±³æ‰‹è¡¨](https://bit.lvbyte.top)'
    'ç¤¾äº¤':
      - '[å‹é“¾](/friend/)'
      - '[æœ‹å‹åœˆ](/friend/rss/)'
      - '[ç•™è¨€æ¿](/about/#comments)'
    'æ›´å¤š':
      - '[å…³äºæœ¬ç«™](/about/)'
      - '[rss](/atom.xml)'
      - '[GitHub](https://github.com/Bytelv)'
  source: '[GitHub](https://github.com/Bytelv/myblog/)' 



# é»˜è®¤å…³é—­
#scrollreveal:
#  enable: true
#  js: https://gcore.jsdelivr.net/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
#  distance: 4px # æ‰§è¡Œè·ç¦»
#  duration: 400 # ms # æ‰§è¡Œæ—¶é•¿
#  interval: 100 # ms # æ‰§è¡Œé—´éš”ï¼ˆæ—¶é—´ï¼‰
#  scale: 0.1 # 0.1~1 # æ‰§è¡Œæ–¹å¼ï¼ˆç¼©æ”¾ï¼‰


 
  
  
tag_plugins:
  # {% image %}
  image:
    fancybox: true


style:
  gradient: # https://webgradients.com/
    start: 'linear-gradient(to right, #92fe9d 0%, #00c9ff 50%, #92fe9d 100%)'
    search: 'linear-gradient(to right, #04F3FF, #08FFC6, #DDF730, #FFBD19, #FF1FE0, #C418FF, #04F3FF)'
  font-family:
    logo: 'HarmonyOS_Medium'
    body: 'HarmonyOS_Regular'
    code: Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif
  codeblock:
    highlightjs_theme: https://cdn.seclusion.work/public/web/stellar-1.18.5/ZYCode.css
